### ISSUE TITLE
Programmatic usage

### ISSUE THREAD

**Issue by vladshcherbin** [holmok/pino-tiny#1]
Hey 👋 

Wondering if it's possible to use `pino-tiny`  similar to [colada example](https://github.com/lrlna/pino-colada#programmatic-integration-as-pino-prettifier)?

Thanks

**Comment by holmok** [comment]
Currently, it does not.  But that could be implemented.  I will mark you as a reviewer on the PR before I merge it.  I will start on it in a few days.  Thanks!

**Comment by holmok** [comment]
It's now available via verion 2.0.0
